project:
  type: book
  output-dir: docs

book:
  title: "Text as Data"
  author: "andrés castro araújo"
  date: last-modified
  chapters:
    - index.qmd
    - intro.qmd
    - part: basics-bow.qmd
      chapters:
        - basics-language-models.qmd
        - basics-vector-spaces.qmd
        - basics-word-embeddings.qmd
    - part: discovery.qmd
    - part: measurement.qmd
    - part: prediction.qmd
    - part: causal.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: lumen
    mainfont: Amiri
    monofont: Fira Code
    fontsize: 1em

fig-align: center

execute:
  freeze: auto

editor: visual
